### ISSUE TITLE
Simplifying pp.spat8~ & pp.out-8~ to 4-channel versions

### ISSUE THREAD

**Issue by thesoundofthesound** [solipd/AudioLab#2]
Hello, 

I'm really enjoying these externals. I think it's great that these are totally Vanilla compatible. 

I'd would like to adapt the 8-channel spatialisation abstraction you've made to a 4-channel version. I've tried modifying the external myself but I am not completely sure if I am not sure if I'm doing everything correctly and was wondering if you could offer some guidance?

Thanks!

**Comment by solipd** [comment]
thanks :)

i added a 4 channel spatializer "pp.spat4~" and the complementary output abstraction "pp.out-4~"

**Comment by delmenhorst** [comment]
😎

**Comment by thesoundofthesound** [comment]
you are very kind and wonderful!
