### ISSUE TITLE
Confusing behaviour of save and recall functions

### ISSUE THREAD

**Issue by thesoundofthesound** [solipd/AudioLab#3]
Thanks for your library. It's such a great resource of patches. 

I've been using your pp.parameq~ and pp.dynamics~ objects in a patch of mine recently. However, I seem to be having odd problems with them when it comes to saving states and recalling them. 

If I use [save $1( and then [recall $1(, I don't always get the saved settings recalled. I saved one preset to bank 1 and I've been able to recall that. But I don't seem to be able to then overwrite that preset and recall the new one. 

I have multiple parameqs running (some in abstractions too, nested within the main patch). I assume that there's some kind of conflict going on, but I'm not sure. 

Any ideas?

**Comment by solipd** [comment]
The issue in pp.parameq~ should be fixed with the latest commit. Can you test it?
It is not clear from your post if you had problems with other objects as well.

**Comment by thesoundofthesound** [comment]
Seems to be working so far. I'll let you know if I come across anything else. Thanks for looking at this!
