### ISSUE TITLE
pp.dynamics-st~ not saving peak/rms option

### ISSUE THREAD

**Issue by thesoundofthesound** [solipd/AudioLab#4]
Hi, me again. 

I'm noticing the the pp.dynamics-st~ patch is not saving the rms option when I save a setting for later recall. It always reverts back to the default of using the peak option. 

Just thought I'd point this out. The save/recall works fine for the mono version of pp.dynamics~

Cheers!

**Comment by solipd** [comment]
Hi and thanks for reporting! This should be fixed with the latest commit. Also note that rms is now the default.
