### ISSUE TITLE
audio signal outlet connected to nonsignal inlet (ignored)

### ISSUE THREAD

**Issue by mk-archaeo** [solipd/AudioLab#6]
Hi,
thanks for this nice repo and the nice examples!
It's not a big issue, but there are some patches where [pow~] is initialized with a number so the right inlet becomes an control inlet, but the incomming data is at audio-rate (see the attached pic). It works, but the console complains about this all the time ;-).
Maybe the initialized value can come to [pow~] in another way.

Thanks
Marco

![PD-powInlet](https://github.com/solipd/AudioLab/assets/4112818/e5fb54be-d637-47af-9251-304ab0898d9f)

**Comment by solipd** [comment]
Hi,
thanks for reporting, but I can not trace this bug. Can you be more specific? Which patch does the picture refer to?

**Comment by mk-archaeo** [comment]
Hi,
this is the damping function in [pp.spacer~]. I've imported it with [declare -path audiolab] in my patch. When I hit Save the message is posted two times (for the right and left function).
In [pp.dopplerxy~] and [pp.doppler~] it is in the amplitude-function.
All debug-levels greater then zero reports this message.

Marco

**Comment by solipd** [comment]
Are you referring to the latest master? This issue should have been fixed in 10a2100 and 89feba1.

**Comment by mk-archaeo** [comment]
Hi,
ahh okay. I downloaded it from deken, one or two weeks ago.
Sorry for the noise ;-)

Marco

**Comment by solipd** [comment]
Something went wrong with the latest deken upload. Uncheck the "only show newest version of a library" option in deken prefences and download v.0.5. But a clone from Github is of course the preferred method if you want to follow the latest development ;) I'll close this issue now
